default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>
  username: <%= ENV["POSTGRES_USER"] || "stat_user" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || 'dev-only:J4z3H9OKmPj7Kd5sVJxpaMY2Z4ilW67QAQ==zGtG9Y5fJFggwzeb' %>

development:
  <<: *default
  database: baseball_stats_development

test:
  <<: *default
  database: baseball_stats_test

production:
  <<: *default
  database: baseball_stats_production
  username: baseball_stats
  password: <%= ENV['BASEBALL_STATS_DATABASE_PASSWORD'] %>
